#!/Users/alikhil/anaconda/bin/python
# -*- coding: utf-8 -*-

import sys
from jinja2 import Environment, Template, meta

def main():
    args = sys.argv[1:]
    if len(args) == 0:
        print('error: path to file not provided')
        exit(1)

    for path in args:
        try:
            env = Environment()
            with open(path, "r") as template:
                template_text = template.read()
                t = env.parse(template_text)
                tt = Template(template_text)
                unvars = meta.find_undeclared_variables(t)
                variables = {}
                for key in unvars:
                    variables[key] = key

                print(tt.render(**variables))

        except Exception as e:
            print('failed to parse and preview ' + path + ': ' + str(e))
    

if __name__ == "__main__":
    main()